# OpenTelemetry Collector Runtime Configuration
# Minimal config for testing embedded Prometheus exporters

# Receivers collect telemetry data
receivers:
  # OTLP receiver - kept to meet minimum requirements
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  # Test exporter receiver - verifies the framework works
  prometheus_testexporter:
    scrape_interval: 10s
    exporter_config:
      exporter_name: "my-test-exporter"

# Exporters send telemetry to backends
exporters:
  # Debug exporter prints to stdout - useful for testing
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

# Service defines the telemetry pipelines
service:
  pipelines:
    # Metrics pipeline - where embedded exporters will send data
    metrics:
      receivers: [otlp, prometheus_testexporter]
      exporters: [debug]

  # Telemetry configuration for the collector itself
  telemetry:
    logs:
      level: info
      development: true
      encoding: console
