formatters:
  enable:
    - goimports
linters:
  enable:
    - misspell
    - revive
  exclusions:
    generated: strict
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test.go
    warn-unused: true
  settings:
    errcheck:
      exclude-functions:
        # Used in HTTP handlers, any error is handled by the server itself.
        - (net/http.ResponseWriter).Write
    revive:
      rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
        - name: unused-parameter
          severity: warning
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1005 # FIXME: Incorrectly formatted error string
version: "2"
