---
name: CI
on:
  pull_request:
  push:
    branches: [main, master, 'release-*']
    tags: ['v*']

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - "1.25"
          - "1.26"
    container:
      image: quay.io/prometheus/golang-builder:${{ matrix.go_version }}-base
    env:
      # Override Go 1.18 security deprecations.
      GODEBUG: "x509sha1=1,tls10default=1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: prometheus/promci-setup@5af30ba8c199a91d6c04ebdc3c48e630e355f62d # v0.1.0
      - run: make test
